version: '3.1'

services:

  db:
    image: postgres
    container_name: tutorialsDjango
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: jasurito
      POSTGRES_DB: db01
      PGDATA: F:\djangodirect\postgres\data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"